services:
  grafana-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: grafana_lgtm_container
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    networks:
      - appointme-network
    restart: unless-stopped

  mail-dev:
    image: maildev/maildev
    container_name: maildev_container
    ports:
      - ${MAILDEV_PORT:-1080}:1080
      - ${SMTP_PORT:-1025}:1025

  mongo:
    image: mongo:${MONGO_VER:-latest}
    restart: always
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:  ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD:  ${MONGO_PASSWORD}

  postgres:
    image: postgres:${POSTGRES_VER:-latest}
    container_name: postgres_container
    labels:
      org.springframework.boot.ignore: true
      app: appointme-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database/db-users/init:/docker-entrypoint-initdb.d
      - ./database/db-users/data:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - appointme-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VER:-24.0.2}
    container_name: keycloak_container
    env_file:
      - .env
    ports:
      - ${KEYCLOAK_PORT:-8080}:8080
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_USER_PASSWORD: ${KEYCLOAK_USER_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - appointme-network
    command:
      - "start-dev"

networks:
  appointme-network:
    driver: bridge
