application:
  file:
    upload-dir: ${BUSINESSES_FILES_DIR:./uploads/businesses/}
    max-file-size: 10MB

spring:
  banner:
    location: classpath:banner-dev.txt
  datasource:
    url: jdbc:postgresql://${APPME_PG_SRV:localhost}:${APPME_PG_PORT:5532}/${APPME_PG_DBNAME:appme_businesses}
    username: ${POSTGRES_USER:pguser}
    password: ${POSTGRES_PASSWORD:p@ssw0rD!}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: businesses-hikari
      minimum-idle: 2
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${SRV_PORT:8082}

categories:
  service:
    url: ${CATEGORIES_SERVICE_URL:http://localhost:8083}

feign:
  client:
    config:
      categories:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic

logging:
  level:
    eu.dec21.appointme: debug
    org.springframework: info
    org.hibernate.SQL: debug