spring:
  profiles:
    active: ${APP_PROFILE:dev}
  web:
    error:
      include-message: always
      include-stacktrace: never
      include-path: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
application:
  title: AppointMe - Businesses
  version: 0.0.1
  date: Jan-02-2026
