application:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
  file:
    upload-dir: ${USER_FILES_DIR:./uploads/users/}
    max-file-size: 10MB

spring:
  datasource:
    url: jdbc:postgresql://${APPME_PG_SRV:localhost}:${APPME_PG_PORT:5532}/${APPME_PG_DBNAME:appme_users}
    username: ${POSTGRES_USER:pguser}
    password: ${POSTGRES_PASSWORD:p@ssw0rD!}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: ivan
    password: ivan
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  banner:
    location: classpath:banner-test.txt

server:
  port: ${SRV_PORT:8081}

logging:
  level:
    eu.dec21.appointme: debug
    org.springframework: info
    org.springframework.security: debug
    org.hibernate.SQL: debug