application:
  frontend:
    url: ${FRONTEND_URL}
  file:
    upload-dir: ${USER_FILES_DIR:/var/appointme/uploads/users/}
    max-file-size: 10MB

spring:
  datasource:
    url: jdbc:postgresql://${APPME_PG_SRV:localhost}:${APPME_PG_PORT:5432}/${APPME_PG_DBNAME:appme_users}
    username: ${POSTGRES_USER:pguser}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: users-hikari
      minimum-idle: 2
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  banner:
    location: classpath:banner-stage.txt

logging:
  level:
    eu.dec21.appointme: info
    org.springframework: info
    org.hibernate: info

server:
  port: ${SRV_PORT:8080}