[versions]
jjwt = "0.13.0"
springdoc = "3.0.1"
jspecify = "1.0.0"
springCloud = "2025.1.1"
testcontainers = "2.0.3"
wiremock = "3.13.2"
awaitility = "4.3.0"

[libraries]
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
spring-cloud-bom = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloud" }
spring-cloud-starter-openfeign = { module = "org.springframework.cloud:spring-cloud-starter-openfeign" }

testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }

wiremock-standalone = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
